CREATE DATABASE IF NOT EXISTS fastsmsh_newup CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'fastsmsh_newup'@'localhost' IDENTIFIED BY 'fastsmsh_newup';
GRANT ALL PRIVILEGES ON fastsmsh_newup.* TO 'fastsmsh_newup'@'localhost';
FLUSH PRIVILEGES;

USE fastsmsh_newup;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  email VARCHAR(191) NOT NULL,
  phone VARCHAR(32) DEFAULT NULL,
  country VARCHAR(64) DEFAULT 'Nigeria',
  password VARCHAR(255) NOT NULL,
  pin VARCHAR(255) DEFAULT NULL,
  ref_code VARCHAR(32) DEFAULT NULL,
  referred_by INT UNSIGNED DEFAULT NULL,
  google_id VARCHAR(128) DEFAULT NULL,
  reset_token VARCHAR(128) DEFAULT NULL,
  reset_expires DATETIME DEFAULT NULL,
  pin_reset_token VARCHAR(128) DEFAULT NULL,
  pin_reset_expires DATETIME DEFAULT NULL,
  balance DECIMAL(18,6) NOT NULL DEFAULT 0,
  currency VARCHAR(8) NOT NULL DEFAULT 'USD',
  total_spent DECIMAL(18,6) NOT NULL DEFAULT 0,
  badge_tier TINYINT NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  first_deposit_at DATETIME DEFAULT NULL,
  last_login DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_users_username (username),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  email VARCHAR(191) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'superadmin',
  last_login DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_admin_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS site_settings (
  `key` VARCHAR(120) NOT NULL PRIMARY KEY,
  `value` TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_gateways (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  gateway VARCHAR(64) NOT NULL,
  public_key TEXT,
  secret_key TEXT,
  extra TEXT,
  extra2 TEXT,
  txn_pin VARCHAR(64) DEFAULT NULL,
  business_name VARCHAR(191) DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uq_gateway (gateway)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wallet_transactions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  type VARCHAR(16) NOT NULL,
  amount DECIMAL(18,6) NOT NULL DEFAULT 0,
  description VARCHAR(255) DEFAULT NULL,
  reference VARCHAR(191) DEFAULT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'success',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_wt_user (user_id),
  KEY idx_wt_ref (reference)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS virtual_accounts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  account_number VARCHAR(32) NOT NULL,
  account_name VARCHAR(191) DEFAULT NULL,
  bank_name VARCHAR(191) DEFAULT NULL,
  provider VARCHAR(64) DEFAULT NULL,
  provider_ref VARCHAR(191) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_va_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS otp_orders (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  order_id VARCHAR(128) DEFAULT NULL,
  service VARCHAR(128) DEFAULT NULL,
  service_name VARCHAR(191) DEFAULT NULL,
  country VARCHAR(64) DEFAULT NULL,
  operator VARCHAR(128) DEFAULT NULL,
  phone VARCHAR(64) DEFAULT NULL,
  otp_code VARCHAR(64) DEFAULT NULL,
  amount_paid DECIMAL(18,6) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  refunded TINYINT(1) NOT NULL DEFAULT 0,
  expires_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_otp_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notifications (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(191) NOT NULL,
  message TEXT,
  link_url VARCHAR(255) DEFAULT '#',
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reviews (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  display_name VARCHAR(120) NOT NULL,
  message TEXT,
  rating TINYINT NOT NULL DEFAULT 5,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS support_tickets (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  subject VARCHAR(191) NOT NULL,
  category_id INT UNSIGNED DEFAULT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS support_replies (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ticket_id INT UNSIGNED NOT NULL,
  sender VARCHAR(24) NOT NULL,
  message TEXT,
  attachment VARCHAR(255) DEFAULT NULL,
  is_auto TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS support_categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(120) NOT NULL,
  auto_reply TEXT,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vtu_services (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(120) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  UNIQUE KEY uq_vtu_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vtu_providers (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  service_id INT UNSIGNED NOT NULL,
  provider_code VARCHAR(64) NOT NULL,
  name VARCHAR(120) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vtu_plans (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  provider_id INT UNSIGNED NOT NULL,
  plan_code VARCHAR(64) NOT NULL,
  plan_name VARCHAR(191) NOT NULL,
  cost_price DECIMAL(18,2) NOT NULL DEFAULT 0,
  selling_price DECIMAL(18,2) NOT NULL DEFAULT 0,
  validity VARCHAR(64) DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vtu_orders (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  service_code VARCHAR(64) DEFAULT NULL,
  provider_name VARCHAR(120) DEFAULT NULL,
  plan_name VARCHAR(191) DEFAULT NULL,
  reference VARCHAR(191) DEFAULT NULL,
  recipient VARCHAR(64) DEFAULT NULL,
  amount_ngn DECIMAL(18,2) DEFAULT 0,
  cost_ngn DECIMAL(18,2) DEFAULT 0,
  amount_usd DECIMAL(18,6) DEFAULT 0,
  status VARCHAR(32) DEFAULT 'pending',
  api_response TEXT,
  extra_data TEXT,
  vtunaija_id VARCHAR(128) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS log_categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(120) NOT NULL,
  icon VARCHAR(64) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS log_products (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category_id INT UNSIGNED NOT NULL,
  name VARCHAR(191) NOT NULL,
  description TEXT,
  price_usd DECIMAL(18,6) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS log_stock (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_id INT UNSIGNED NOT NULL,
  credentials TEXT,
  is_sold TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS log_orders (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  total_usd DECIMAL(18,6) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS log_order_items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_id INT UNSIGNED NOT NULL,
  stock_id INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS paymentpoint_logs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  payload LONGTEXT,
  reference VARCHAR(191) DEFAULT NULL,
  amount DECIMAL(18,2) DEFAULT 0,
  status VARCHAR(64) DEFAULT NULL,
  processed TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ncwallet_logs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  payload LONGTEXT,
  reference VARCHAR(191) DEFAULT NULL,
  amount DECIMAL(18,2) DEFAULT 0,
  status VARCHAR(64) DEFAULT NULL,
  processed TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO payment_gateways (gateway, is_active) VALUES
  ('paymentpoint', 0),
  ('ncwallet', 0),
  ('paystack', 0),
  ('sprintpay', 1);

INSERT IGNORE INTO site_settings (`key`, `value`) VALUES
  ('site_name', 'FastSmsHub'),
  ('usd_ngn_fallback_rate', '1600'),
  ('min_topup_usd', '1'),
  ('max_topup_usd', '50');

INSERT IGNORE INTO vtu_services (code, name, is_active) VALUES
  ('airtime', 'Airtime', 1),
  ('data', 'Data', 1),
  ('cable', 'Cable', 1),
  ('electricity', 'Electricity', 1);
